# Generated by Django 3.2.7 on 2021-11-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
